name: deploy

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.5.2
      - name: yarn install
        run: npm install --global yarn
      - name: build
        run: |
          yarn install
          yarn build
      - name: install firebase tools
        run: sudo npm install -g firebase-tools
      - name: deploy to firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
